questions = [
    {"category": "Vision", 
     "question": "Have you noticed any sudden changes in your vision, such as blurred or distorted vision?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9GzLhdDzfRTL0MQmvnPqqnKBI6HnSGIsq2Q&s"},

    {"category": "Vision", 
     "question": "Do you experience difficulty in seeing at night or in low-light conditions?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9GzLhdDzfRTL0MQmvnPqqnKBI6HnSGIsq2Q&s"},

    {"category": "Vision", 
     "question": "Are there any dark spots or floaters in your vision that appear to drift across your field of view?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9GzLhdDzfRTL0MQmvnPqqnKBI6HnSGIsq2Q&s"},

    {"category": "Eye Symptoms", 
     "question": "Do you experience frequent eye pain or discomfort?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://static.thenounproject.com/png/3650745-200.png"},

    {"category": "Eye Symptoms", 
     "question": "Have you noticed any redness or inflammation in your eyes?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0},
     "type": "button",
     "image":"https://static.thenounproject.com/png/3650745-200.png"},

    {"category": "Eye Symptoms", 
     "question": "Are your eyes more sensitive to light than usual?", 
     "options": {"Yes": 1, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://static.thenounproject.com/png/3650745-200.png"},

    {"category": "Medical History", 
     "question": "How well have you been managing your blood sugar levels?", 
     "options": {"Poorly": 3, "Moderately": 2, "Well": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://cdn-icons-png.flaticon.com/512/181/181910.png"},

    {"category": "Medical History", 
     "question": "Do you have high blood pressure or cholesterol levels?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://cdn-icons-png.flaticon.com/512/181/181910.png"},

    {"category": "Medical History", 
     "question": "Have you had diabetes for a long period (more than 5-10 years)?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://cdn-icons-png.flaticon.com/512/181/181910.png"},

    {"category": "Routine Eye Exams", 
     "question": "When was your last comprehensive eye exam by an eye specialist?", 
     "options": {"More than a year ago": 3, "Within the last year": 1, "Within the last six months": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://static.vecteezy.com/system/resources/previews/003/703/942/original/icon-of-eye-exam-5-glyph-style-free-vector.jpg"},

    {"category": "Routine Eye Exams", 
     "question": "Have you ever been diagnosed with any eye conditions related to diabetes?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://static.vecteezy.com/system/resources/previews/003/703/942/original/icon-of-eye-exam-5-glyph-style-free-vector.jpg"},

    {"category": "General Health", 
     "question": "Are you taking any medications for diabetes, and are you consistent with them?", 
     "options": {"No": 3, "Sometimes": 2, "Yes": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://png.pngtree.com/png-vector/20190328/ourmid/pngtree-vector-health-icon-c-png-image_872167.jpg"},

    {"category": "General Health", 
     "question": "Have you experienced any sudden weight changes recently?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://png.pngtree.com/png-vector/20190328/ourmid/pngtree-vector-health-icon-c-png-image_872167.jpg"},

    {"category": "General Health", 
     "question": "Do you have any other chronic conditions that could affect your vision?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://png.pngtree.com/png-vector/20190328/ourmid/pngtree-vector-health-icon-c-png-image_872167.jpg"},

    {"category": "Additional Questions", 
     "question": "How often do you use tobacco products?", 
     "options": {"Very Often": 3, "Once in a while": 0, "Never": 0, "Prefer not to answer": 0}, 
     "type":"button",
     "image":"https://toppng.com/uploads/preview/add-new-questions-add-question-icon-1156298351152eixf9qfh.png"},

    {"category": "Additional Questions", 
     "question": "Do you engage in regular physical activity?", 
     "options": {"3-4 times a week": 0, "1-2 times a week": 1, "Less than once a week": 2, "Never": 3, "Not sure": 0}, 
     "type": "button",
     "image":"https://toppng.com/uploads/preview/add-new-questions-add-question-icon-1156298351152eixf9qfh.png"},

    {"category": "Additional Questions", 
     "question": "How often do you follow a balanced diet that includes vegetables, fruits, and whole grains?", 
     "options": {"3-4 times a week": 0, "1-2 times a week": 1, "Less than once a week": 2, "Never": 3, "Not sure": 0}, 
     "type": "button",
     "image":"https://toppng.com/uploads/preview/add-new-questions-add-question-icon-1156298351152eixf9qfh.png"},

    {"category": "Additional Questions", 
     "question": "What is your BMI", 
     "options": {"Below 18.5": 0, "18.5-24.9": 0, "25.0-29.9": 0, "Above 30.0": 0}, 
     "type":"button",
     "image":"https://toppng.com/uploads/preview/add-new-questions-add-question-icon-1156298351152eixf9qfh.png"},
    
    {"category": "Additional Questions", 
     "question": "How many glasses of water do you drink daily?", 
     "options": {"Less than 4": 1, "4-6": 1, "7-9": 0, "10 or more": 0, "Not sure": 0}, 
     "type":"button",
     "image":"https://toppng.com/uploads/preview/add-new-questions-add-question-icon-1156298351152eixf9qfh.png"},
]