questions = [
    {"category": "Vision", 
     "question": "Have you noticed any sudden changes in your vision, such as blurred or distorted vision?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Vision", 
     "question": "Do you experience difficulty in seeing at night or in low-light conditions?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Vision", 
     "question": "Are there any dark spots or floaters in your vision that appear to drift across your field of view?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Eye Symptoms", 
     "question": "Do you experience frequent eye pain or discomfort?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Eye Symptoms", 
     "question": "Have you noticed any redness or inflammation in your eyes?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0},
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Eye Symptoms", 
     "question": "Are your eyes more sensitive to light than usual?", 
     "options": {"Yes": 1, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Medical History", 
     "question": "How well have you been managing your blood sugar levels?", 
     "options": {"Poorly": 3, "Moderately": 2, "Well": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Medical History", 
     "question": "Do you have high blood pressure or cholesterol levels?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Medical History", 
     "question": "Have you had diabetes for a long period (more than 5-10 years)?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Routine Eye Exams", 
     "question": "When was your last comprehensive eye exam by an eye specialist?", 
     "options": {"More than a year ago": 3, "Within the last year": 1, "Within the last six months": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Routine Eye Exams", 
     "question": "Have you ever been diagnosed with any eye conditions related to diabetes?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "General Health", 
     "question": "Are you taking any medications for diabetes, and are you consistent with them?", 
     "options": {"No": 3, "Sometimes": 2, "Yes": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "General Health", 
     "question": "Have you experienced any sudden weight changes recently?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "General Health", 
     "question": "Do you have any other chronic conditions that could affect your vision?", 
     "options": {"Yes": 2, "No": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Additional Questions", 
     "question": "Do you smoke or use tobacco products?", 
     "options": {"Yes": 3, "No": 0, "Not sure": 0}, 
     "type":"button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Additional Questions", 
     "question": "Do you engage in regular physical activity (at least 30 minutes, 3 times a week)?", 
     "options": {"No": 2, "Yes": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Additional Questions", 
     "question": "Do you follow a balanced diet that includes vegetables, fruits, and whole grains?", 
     "options": {"No": 2, "Yes": 0, "Not sure": 0}, 
     "type": "button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},

    {"category": "Additional Questions", 
     "question": "What is your BMI", 
     "options": {"Below 18.5": 0, "18.5-24.9": 0, "25.0-29.9": 0, "Above 30.0": 0}, 
     "type":"button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},
    
    {"category": "Additional Questions", 
     "question": "Do you drink at least 8 glasses of water daily?", 
     "options": {"No": 1, "Yes": 0, "Not sure": 0}, 
     "type":"button",
     "image":"https://www.wfla.com/wp-content/uploads/sites/71/2023/05/GettyImages-1389862392.jpg?w=2560&h=1440&crop=1"},
]